import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import imag from "../../public/S.png"
import { companyName } from '../commen/CommenName'
import Navbar from '../component/Navbar'
import "./home.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: companyName,
    description: 'Generated by create next app',
    icons: [{ rel: 'icon', url: imag.src }],
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="min-h-screen min-w-full bg-gray-200">
                    <Navbar page="" />
                    {children}
                </div>
            </body>
        </html>
    )
}
