import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import imag from "../public/S.png";
import { companyName } from "./commen/CommenName";
import Navbar from "./component/Navbar";
import Layout from "./component/LayoutComponent/Route";
import { Providers } from "@/redux/provider/provider";
import { AuthProvider } from "./auth/Provider";
import { store } from "@/redux/store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: companyName,
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: imag.src }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" data-theme={"dark"}>
      <body className={inter.className}>
        <AuthProvider>
          <div className="min-h-screen min-w-full overflow-hidden">
            {/* <Navbar page="main" /> */}

            <main>
              <Providers>
                <Layout />
                {children}
              </Providers>
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
